### ISSUE TITLE
Search ArangoDB installations on all drives in Windows

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/arangodb#4]
Customer wanted to install ArangoDB under E:\arangodb. Obviously, the starter would not find the installation there. Override with `--arangod` and `--jsDir` worked. Maybe we should at least look into all drives?

**Comment by ewoutp** [comment]
I would very much prefer to add a search using the PATH envvar.
If that still fails, people have a very specific setup and that is exactly what `--arangod` and `--jsDir` are for.

**Comment by neunhoef** [comment]
Good argument, we should search the PATH for the executable and discover the jsDir from the executable we find. And yes, `--arangod` and `--jsDir` are for cases that cannot be caught with this.

**Comment by dothebart** [comment]
currently the binaries try to step up from their location to locate the top level directory of the installation and their respective configuration; i.e. 

`c:/Progra~1/ArangoDB 3.1.12/usr/bin/arangod.exe` will search in `c:/Progra~1/ArangoDB 3.1.12/etc/arangodb3/arangod.conf`

**Comment by sleto-it** [comment]
I think this may not be relevant anymore - perhaps when the issue was opened the starter was not yet part of the official arangodb distribution (just wondering)?

One can always starts command in the following way - with the advantage of being sure of what exactly it is being started (in case more versions are present in the system):

"D:\qa\3.2.9\ArangoDB3e-3.2.9-1_win64\usr\bin\arangodb.exe" --starter.data-dir=C:\qa\3.2.9\node1
"D:\qa\3.2.9\ArangoDB3e-3.2.9-1_win64\usr\bin\arangodb.exe" --starter.data-dir=C:\qa\3.2.9\node2 --starter.join 127.0.0.1
"D:\qa\3.2.9\ArangoDB3e-3.2.9-1_win64\usr\bin\arangodb.exe" --starter.data-dir=C:\qa\3.2.9\node3 --starter.join 127.0.0.1

(in this case data is stored in C and ArangoDB is unpacked in D)

Hope this helps,

**Comment by ewoutp** [comment]
I agree with @sleto-it that this is not really relevant anymore now that the starter is included in the distribution.
Closing it.
