### ISSUE TITLE
Can a Docker cluster be restarted ?

### ISSUE THREAD

**Issue by yellowiscool** [arangodb-helper/arangodb#59]
Hi,

I used arangodb with Docker and I noticed that the containers do not restart by default. I updated them using `docker update --restart=always {mycontainersids}` but could you explain why a restart strategy is not set by default ?

**Comment by ewoutp** [comment]
This is not turned on by default, because we assume that you start the Starter using some init script (systemd...) which will just restart the containers for you.

We'll consider adding an option for this.

**Comment by ewoutp** [comment]
While the concept of a restart sounds very reasonable, there is actually one more issue with it. 
When the Starter terminates, it actively stops the created containers (this is very much by design). So the only way for the containers to be in a state where the docker daemon can restart them it upon a power failure or a very hard kill of the starter.

Therefore you're best of using the starter directly from you init system.

**Comment by yellowiscool** [comment]
I don't really have init scripts on my Docker Swarm cluster. Some nodes are running SystemD, some are still running Upstart. I prefer to use Docker for this kind of thing, but I get your point. An option would be convenient.

I killed the starters (`docker kill adb`) and Arango seems to go well without it. Is the starter required only for starting the containers, or does it also monitor the services ? An option to exit the starter without killing containers when the deployement is done would be interesting too.

**Comment by ewoutp** [comment]
The starter monitors the started containers/process and takes care of restarting them when needed.
