### ISSUE TITLE
Error while running Docker in Marathon

### ISSUE THREAD

**Issue by Huma123** [arangodb-helper/arangodb#87]
Trying to setup Docker Cluster in Marathon 

While starting the first docker container I am getting the followng error 

2017/10/05 18:34:14 Starting arangodb version 0.9.3, build c185373
2017/10/05 18:34:14 Cannot find docker container name. Please specify using --dockerContainer=...

**Comment by ewoutp** [comment]
When running in docker (under control of whatever scheduler) the starter needs to know its container name, so it can ask docker for its port mapping.

Please try to add the indicated option to the starter command line.

**Comment by neunhoef** [comment]
One problem I foresee is that the starter currently needs a range of 4 adjacent ports. Using Marathon it is not guaranteed that one gets this. Furthermore, since the starter task is probably not allowed to use the Docker API to start other Docker containers for the ArangoDB tasks and since it does not know how to use Mesos/Marathon to start tasks using Mesos, the only possiblity I see is to let the starter start multiple processes in the same container. Then you need the port range. I once got it to work in an experiment, but it this approach is totally against the philosophy of Mesos/Marathon and therefore I have given up on it.

**Comment by dothebart** [comment]
Closing as "won't fix"
