### ISSUE TITLE
Remove thread & v8-context settings from generated arangod.conf

### ISSUE THREAD

**Issue by ewoutp** [arangodb-helper/arangodb#94]
- server.threads
- javascript.v8-contexts

@neunhoef Please confirm this is safe in 3.1 & 3.2

**Comment by neunhoef** [comment]
Dynamic V8 contexts were introduced just before the release of 3.2, so 3.1 does not have them yet.
For 3.1 it would probably be better to leave the settings for v8 contexts. However, old installation will not automatically change since the options are in the config. There I suggest to remove the options now.
